version: "3.8"
services:
  frontend:
    restart: unless-stopped
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    environment:
       - CHOKIDAR_USEPOLLING=true