name: React Template Deploy Frontend # will be changed according to the project

on:
  push:
    branches: [ prod ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  pull_code:
    uses: ./.github/workflows/pull_code.yml
    secrets: inherit
  deploy-fe:
    runs-on: ubuntu-latest
    needs: pull_code
    steps:
      - uses: actions/checkout@main  
      - name: Run remote ssh commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          script_stop: true
          # Every $ will be changed according to the project
          script: |
            cd /var/www/html/$ONG/$YEAR/$TYPE_OF_PROJECT/$PROJECT_NAME/frontend
            npm ci
            npm run build
            cd server
            npm ci
            rm -r ../old_build 2>/dev/null
            mv ../dist/ ../old_build
            pm2 stop fe || true
            pm2 delete fe || true
            pm2 start --name "fe" deploy.js