name: React Template Pull code # will be changed according to the project

on:
  workflow_call:
  workflow_dispatch:

jobs: 
  pull_code:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}} # key generated on the server
          host: ${{secrets.HOST_PROD}}
          username: ${{secrets.USERNAME}}
          script_stop: true
          # Every $ will be changed according to the project
          script: |
            cd /var/www/html/$ONG/$YEAR/$TYPE_OF_PROJECT/$PROJECT_NAME
            git checkout prod
            git pull origin prod